package com.xzavier0722.mc.plugin.slimefun4.storage.controller;

import static org.junit.jupiter.api.Assertions.*;

import com.xzavier0722.mc.plugin.slimefun4.storage.common.FieldKey;
import com.xzavier0722.mc.plugin.slimefun4.storage.common.RecordSet;
import com.xzavier0722.mc.plugin.slimefun4.storage.util.ItemStackDataCodec;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.util.io.BukkitObjectOutputStream;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockbukkit.mockbukkit.MockBukkit;

/** Reads historical encodings generated by this harness, not claimed historical-world captures. */
class StoredInventoryReaderTest {
    @BeforeEach
    void setUp() {
        MockBukkit.mock();
    }

    @AfterEach
    void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    void preservesNativeLegacyAndTextWrappedItemsAndOriginalRows() throws Exception {
        ItemStack item = item();
        byte[] nativeBytes = ItemStackDataCodec.serialize(item);
        byte[] legacy = legacy(item);
        for (Object raw : List.of(
                nativeBytes,
                legacy,
                new String(legacy, StandardCharsets.US_ASCII),
                Base64.getEncoder().encodeToString(nativeBytes),
                Base64.getEncoder().encode(nativeBytes))) {
            RecordSet record = row("8", raw);
            record.readonly();
            ItemStack[] inventory = StoredInventoryReader.read(List.of(record), 9, "old-backpack");
            assertEquals(37, inventory[8].getAmount());
            assertEquals(item.getItemMeta(), inventory[8].getItemMeta());
            assertNull(inventory[0]);
            if (raw instanceof byte[] bytes) {
                assertArrayEquals(bytes, (byte[]) record.getValue(FieldKey.INVENTORY_ITEM));
            } else {
                assertEquals(raw, record.getValue(FieldKey.INVENTORY_ITEM));
            }
        }
    }

    @Test
    void retainsHistoricalEmptyRepresentations() {
        List<RecordSet> rows = Arrays.asList(row("0", null), row("1", ""), row("2", " \n"), row("3", new byte[0]));
        ItemStack[] items = StoredInventoryReader.read(rows, 9, "empty");
        assertFalse(StoredInventoryReader.hasItems(items));
        assertEquals(9, items.length);
    }

    @ParameterizedTest
    @ValueSource(strings = {"-1", "9", "54", "NaN", "2147483648", ""})
    void rejectsInvalidSlotWithoutPublishingOrChangingRows(String slot) {
        RecordSet valid = row("0", ItemStackDataCodec.serialize(item()));
        RecordSet invalid = row(slot, ItemStackDataCodec.serialize(item()));
        Object original = invalid.getValue(FieldKey.INVENTORY_ITEM);
        assertThrows(
                IllegalStateException.class, () -> StoredInventoryReader.read(List.of(valid, invalid), 9, "owner"));
        assertSame(original, invalid.getValue(FieldKey.INVENTORY_ITEM));
    }

    @Test
    void rejectsMissingOrDuplicatedSlots() {
        RecordSet missingSlot = new RecordSet();
        missingSlot.put(FieldKey.INVENTORY_ITEM, ItemStackDataCodec.serialize(item()));
        assertThrows(IllegalStateException.class, () -> StoredInventoryReader.read(List.of(missingSlot), 9, "owner"));
        assertThrows(
                IllegalStateException.class,
                () -> StoredInventoryReader.read(List.of(row("1", ""), row("01", "")), 9, "owner"));
    }

    @Test
    void nonEmptyDataCannotBeSilentlyReadAsNullOrAir() {
        for (ItemStack outcome : Arrays.asList(null, new ItemStack(Material.AIR))) {
            RecordSet record = new RecordSet() {
                @Override
                public ItemStack getItemStack(FieldKey field) {
                    return outcome;
                }
            };
            record.put(FieldKey.INVENTORY_SLOT, "0");
            record.put(FieldKey.INVENTORY_ITEM, "non-empty-opaque-item");
            assertThrows(IllegalStateException.class, () -> StoredInventoryReader.read(List.of(record), 9, "owner"));
        }
    }

    @Test
    void rejectsUnknownStorageTypeAndContainsLinkageFailure() {
        RecordSet unsupported = new RecordSet() {
            @Override
            public Object getValue(FieldKey key) {
                return 123;
            }
        };
        unsupported.put(FieldKey.INVENTORY_SLOT, "0");
        assertThrows(IllegalStateException.class, () -> StoredInventoryReader.read(List.of(unsupported), 9, "owner"));
        RecordSet linkage = new RecordSet() {
            @Override
            public ItemStack getItemStack(FieldKey key) {
                throw new NoClassDefFoundError("missing-addon-class");
            }
        };
        linkage.put(FieldKey.INVENTORY_SLOT, "0");
        linkage.put(FieldKey.INVENTORY_ITEM, "opaque");
        IllegalStateException failure = assertThrows(
                IllegalStateException.class, () -> StoredInventoryReader.read(List.of(linkage), 9, "owner"));
        assertInstanceOf(NoClassDefFoundError.class, failure.getCause());
    }

    @Test
    void invalidSizeAndMalformedPayloadRemainFailuresNotEmptyInventories() {
        for (int size : new int[] {0, -1, 55, Integer.MAX_VALUE}) {
            assertThrows(IllegalStateException.class, () -> StoredInventoryReader.read(List.of(), size, "owner"));
        }
        for (Object raw : List.of(new byte[] {'S', 'F', '2', 0}, "%%%bad-item%%%")) {
            RecordSet bad = row("4", raw);
            assertThrows(
                    IllegalStateException.class,
                    () -> StoredInventoryReader.read(
                            List.of(row("0", ItemStackDataCodec.serialize(item())), bad), 9, "owner"));
        }
    }

    static RecordSet row(String slot, Object raw) {
        RecordSet row = new RecordSet();
        row.put(FieldKey.INVENTORY_SLOT, slot);
        if (raw instanceof byte[] bytes) row.put(FieldKey.INVENTORY_ITEM, bytes);
        else row.put(FieldKey.INVENTORY_ITEM, (String) raw);
        return row;
    }

    static ItemStack item() {
        ItemStack item = new ItemStack(Material.COAL, 37);
        var meta = item.getItemMeta();
        meta.getPersistentDataContainer()
                .set(
                        NamespacedKey.fromString("slimefun:slimefun_item"),
                        PersistentDataType.STRING,
                        "OLD_ADDON_ITEM_ID");
        meta.getPersistentDataContainer()
                .set(NamespacedKey.fromString("oldaddon:capacity"), PersistentDataType.LONG, 9_000_000_001L);
        item.setItemMeta(meta);
        return item;
    }

    @SuppressWarnings("deprecation") // Fixture writer for the retained historical read contract only.
    private static byte[] legacy(ItemStack item) throws Exception {
        try (var bytes = new ByteArrayOutputStream();
                var out = new BukkitObjectOutputStream(bytes)) {
            out.writeObject(item);
            out.flush();
            return Base64.getEncoder().encode(bytes.toByteArray());
        }
    }
}
